#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@File : split_pdb.py
@Time : 2021/11/15 17:15:19
@Author : Wang Zhengjie 
@Version : 1.0
@Contact : wangzhengjie.CN@gmail.com
@License : (C)Copyright 2020-2021, MTSD, China University of Petroleum (East China)
@Desc : None
'''

'''
patch by Zhaoxz
patch ver 1.1
introducing optparse module to get filename and other setting easily.
Contact: xingzezhao9812@163.com
'''

# here put the import lib
from ast import parse
import os
from optparse import OptionParser

# parse arguments for input file names
def command_line_arg():
    usage = "usage: %prog [options] arg1 arg2"
    par = OptionParser(usage=usage)
    par.add_option('-i','--input',
                    action= 'store', type = 'string', dest= 'pdbFilepath',
                    default= './npt.pdb',
                    help= 'location of the PDB file')
    par.add_option('-o','--output',
                    action= 'store', type = 'string', dest= 'saveDir',
                    default= './split_all',
                    help= 'directory to save the splitted PDB files')
    par.add_option('-d','--delta',
                    action= 'store', type = 'int', dest= 'timeDelta',
                    default= '20',
                    help= 'time interval between two flames, in (ps)')  
    return par.parse_args()           

if __name__ == '__main__':
    opts, args = command_line_arg()
    with open(opts.pdbFilepath) as f1:
        lines = f1.readlines()
    end_num = []
    for i,line in enumerate(lines):
        if line.startswith('ENDMDL'):
            end_num.append(i)
    end_num.insert(0,-1)
    save_path = opts.saveDir
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    N=0
    dt = opts.timeDelta
    for i in range(len(end_num)):
        if i < len(end_num)-1:
            start = end_num[i]+1
            end = end_num[i+1]
            with open(os.path.join(save_path,'%s.pdb'%str(N*dt).zfill(6)),'w') as f:
                f.writelines(lines[start:end+1])
            N+=1
        else:
            break
    print('Save %s pdb files'%str(N))
    print('Done!')




